//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public player()
        {
            this.stats = new HashSet<stat>();
        }
    
        public int playerId { get; set; }
        public string fName { get; set; }
        public string lastName { get; set; }
        public string position { get; set; }
        public string team { get; set; }
    
        public virtual ICollection<stat> stats { get; set; }
    }
}
