//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stat
    {
        public Nullable<int> pointsScored { get; set; }
        public Nullable<int> gamesPlayed { get; set; }
        public int Player_playerId { get; set; }
        public Nullable<int> rushingTDs { get; set; }
        public Nullable<int> rushingYDs { get; set; }
        public Nullable<int> fumblesLost { get; set; }
        public Nullable<int> receptions { get; set; }
        public Nullable<int> receivingTDs { get; set; }
        public Nullable<int> receivingYDs { get; set; }
        public Nullable<int> passingYDs { get; set; }
        public Nullable<int> passingINTs { get; set; }
        public Nullable<int> passingTDs { get; set; }
        public Nullable<int> Year { get; set; }
        public string Week { get; set; }
        public int statsID { get; set; }
    
        public virtual player player { get; set; }
    }
}
